# PlayzerX continuous integration workflow
name: PlayzerX-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-windows"
  build-windows-x86:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
          
      # Runs a single command using the runners shell
      - name: Build Debug Win32
        run: msbuild PlayzerX-All.sln /p:Configuration=Debug /p:Platform=Win32
      
      # Runs a single command using the runners shell
      - name: Build Release Win32
        run: msbuild PlayzerX-All.sln /p:Configuration=Release /p:Platform=Win32

   # This workflow contains a single job called "build-windows"
  build-windows-x64:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2
          
      # Runs a single command using the runners shell
      - name: Build Debug x64
        run: msbuild PlayzerX-All.sln /p:Configuration=Debug /p:Platform=x64
      
      # Runs a single command using the runners shell
      - name: Build Release x64
        run: msbuild PlayzerX-All.sln /p:Configuration=Release /p:Platform=x64

  # This workflow contains a single job called "build-ubuntu"
  build-ubuntu-20-04:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install libopencv-dev
        run: |
          sudo apt-get update
          sudo apt-get install libopencv-dev
        
      # Runs a single command using the runners shell
      - name: Build delivery folder (Debug)
        run: ./tools/linux_build_repo.sh Debug

  build-ubuntu-22-04:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Install libopencv-dev
        run: |
          sudo apt-get update
          sudo apt-get install libopencv-dev
        
      # Runs a single command using the runners shell
      - name: Build delivery folder (Debug)
        run: ./tools/linux_build_repo.sh Debug
